#!/bin/sh -e
# postinst for factorio-mutlienv-ctl

set -e

PKG=factorio-mutlienv-ctl
SERVER_VERSION="0.16.39"
SERVER_DL_URL="https://www.factorio.com/get-download/$SERVER_VERSION/headless/linux64"
INSTALL_DIR="/opt/factorio"
TAR_DIR_NAME="factorio"
DATA_DIR="/var/factorio"


if [ "$1" = configure ] ; then
    # Create factorio user if not exists
    id -u factorio > /dev/null || adduser --disabled-login --system --no-create-home --shell /bin/bash --group --gecos factorio factorio

    if grep -q "$SERVER_VERSION" "$INSTALL_DIR/$TAR_DIR_NAME/data/changelog.txt"; then
        echo " => The requested factorio version or newer is already installed: v$SERVER_VERSION"
    else
        # First: if server is running we need to stop it.
        echo " => A update has been found and will be downloaded now."
        echo " => Stopping all factorio servers..."
        systemctl stop 'factorio@*'

        # Then: we remove the old binary folder to ensure no crap is left.
        BINARY_DIR="$INSTALL_DIR/$TAR_DIR_NAME"
        if [ -d "$BINARY_DIR" ]; then
            rm -Rf "$BINARY_DIR"
        fi

        # Lastly: update and extract the (new) game files.
        echo " => Downloading and updating factorio server..."
        mkdir -p "$INSTALL_DIR"
        curl --progress-bar -L "$SERVER_DL_URL" | bsdtar xf - -C "$INSTALL_DIR"

        echo " => Downloading done, factorio install OK."
        echo " => You will have to MANUALLY restart your server(s)."
    fi

    # Set up the folders we need.
    mkdir -p "$INSTALL_DIR/factorio/temp"
    mkdir -p "$DATA_DIR/instances/default/saves"
    mkdir -p "$DATA_DIR/mods"

    # Sets various runtime permissions. Ensures factorio user can access game files.
    chown factorio:factorio "$INSTALL_DIR/factorio"
    chown factorio:factorio "$INSTALL_DIR/factorio/temp"

    chown factorio:factorio "$DATA_DIR"
    chown factorio:factorio "$DATA_DIR/instances"
    chown factorio:factorio "$DATA_DIR/instances/default"
    chown factorio:factorio "$DATA_DIR/instances/default/saves"
    chown factorio:factorio "$DATA_DIR/mods"

fi

#DEBHELPER#

exit 0
