#!/bin/sh -e
# postinst for factorio-mutlienv-ctl

set -e

PKG=factorio-mutlienv-ctl
SERVER_VERSION="0.16.11"
SERVER_DL_URL="https://www.factorio.com/get-download/$SERVER_VERSION/headless/linux64"


if [ "$1" = configure ] ; then
    # Create factorio user if not exists
    id -u factorio > /dev/null || adduser --disabled-login --system --no-create-home --shell /bin/bash --group --gecos factorio factorio

    # Set up the folders we need.
    mkdir -p /opt/factorio/factorio/temp
    mkdir -p /var/factorio/instances/default/saves
    mkdir -p /var/factorio/mods

    # Various runtime permissions
    chown factorio:factorio /opt/factorio/factorio
    chown factorio:factorio /opt/factorio/factorio/temp
    chown factorio:factorio /var/factorio
    chown factorio:factorio /var/factorio/instances
    chown factorio:factorio /var/factorio/instances/default
    chown factorio:factorio /var/factorio/instances/default/saves
    chown factorio:factorio /var/factorio/mods

    if grep -q "$SERVER_VERSION" /opt/factorio/factorio/data/changelog.txt; then
        echo " => The requested factorio version or newer is already installed: v$SERVER_VERSION"
    else
        # First: if server is running we need to stop it.
        echo " => A update has been found and will be downloaded now."
        echo " => Stopping all factorio servers..."
        systemctl stop 'factorio@*'

        echo " => Downloading and updating factorio server..."
        curl --progress-bar -L "$SERVER_DL_URL" | bsdtar xf - -C /opt/factorio/

        echo " => Downloading done, factorio install OK."
        echo " => You will have to MANUALLY restart your server(s)."
    fi
fi

#DEBHELPER#

exit 0
